### ISSUE TITLE
request: Atari 800 XL/XE

### ISSUE THREAD

**Issue by zbyti** [drmortalwombat/oscar64#12]
are there any chances that the binary will be compiled for 8-bit Atari? I know people who can help with that, it's been a waste that this excellent compiler is not multiplatform ;)

**Comment by drmortalwombat** [comment]
the -tf=atari option should take care of it

**Comment by zbyti** [comment]
https://github.com/drmortalwombat/oscar64/issues/6

**Comment by zbyti** [comment]
works fine :)

```c
#define SDMCTL	((char *)0x22F)
#define COLBK	((char *)0xD01A)
#define WSYNC	((char *)0xD40A)
#define VCOUNT	((char *)0xD40B)

int main(void)
{
	*SDMCTL=0;

	for(;;)
	{
		*COLBK=*WSYNC=*VCOUNT;	
	}
}
```
