### ISSUE TITLE
compiling samples/hiresmc/paint.c fails

### ISSUE THREAD

**Issue by spiro-trikaliotis** [drmortalwombat/oscar64#13]
Compiling the samples, paint.c fails:
```
~/oscar64/samples/hiresmc$ ../../bin/oscar64 paint.c -n
corrupted double-linked list
Aborted
```

This is on Debian 11.7, gcc Version "gcc (Debian 10.2.1-6) 10.2.1 20210110". Before running this command, I did a `cd make; make`only.

**Comment by spiro-trikaliotis** [comment]
Works like a charm, thank you -> closing

**Comment by polluks** [comment]
Nice to meet some cc65 guys :-)
