### ISSUE TITLE
Cannot invoke a not default constructor globally

### ISSUE THREAD

**Issue by AGPX** [drmortalwombat/oscar64#143]
The compiler don't allow to declare `foo c(7);` because I'm invoking a non-default constructor globally.

```
#include <stdio.h>

int CN = 0;
int DN = 0;

struct foo {
  int Num;
  foo(int num) : Num(num) {
    printf("Foo ctor %d %d\n", Num, CN++);
  }
  ~foo() {
    printf("Foo dtor %d %d\n", Num, DN++);
  }
};

foo c(7);

struct bar {
    bar() {}
    ~bar() {
        printf("bar dtor\n");
    }
} b;

int main() {
  printf("main\n");
  return 0;
}

```

**Comment by drmortalwombat** [comment]
Fixed, please note that the linker is very aggressive (slightly beyond the language spec), and if you want the "foo c(7)" to be created you have the either reference it or declare it with __export.

**Comment by AGPX** [comment]
Test passed.
