### ISSUE TITLE
Some for loops are running endless

### ISSUE THREAD

**Issue by adaumann** [drmortalwombat/oscar64#161]
In the Orbix game I have a for loop with a nested for loop. The inner loop is running endless without terminating:

    for (byte j = 0; j < 3; j++)
    {
        stepO += 15 * PI / 180;
        float step = stepO;
        for (int i = 0; i < 12; i++)
        {
            step += 30 * PI / 180;
            float x = radius * cos(step) + 160;
            float y = radius * 0.6 * sin(step) + 108;
            if (i % 3 == 0)
            {
                proxy3_setGameObjectTimedValuableCircle(numObjects++, x, y, 6, true);
            }
            else
            {
                proxy3_setGameObjectTimedCircle(numObjects++, x, y, 6, true);
            }
        }
        radius += 30;
    }    

I think you have still access to the repository. It is in function: initScene4_4(). In the version from 28.7 it is working correctly.

**Comment by drmortalwombat** [comment]
It works with the version that is currently checked it, I will prepare a new installation for you to try out, if you are not building the compiler yourself.

**Comment by drmortalwombat** [comment]
New installer uploaded, give it a try

**Comment by adaumann** [comment]
It is working again. Thanks
