### ISSUE TITLE
bool variable value may change randomly in a for loop

### ISSUE THREAD

**Issue by kovzol** [drmortalwombat/oscar64#172]
First of all, thanks for your wonderful work.
I faced the following problem when compiling for C64 (with no extra switches, that is, I use `oscar64 {source.c}` on Linux):
```
#include <stdio.h>

int main() {
    int a = 2;
    bool found = false;
    for (int i=0; i<4 && !found; i++) {
        if (a == i) {
            found = true;
            printf("1 FOUND=%d\n", found);
        }
        printf("2 FOUND=%d\n", found);
    }
    printf("3 FOUND=%d\n", found);
    return 0;
}
```
Here the variable `found` gets the value `true` when `i==2`, but then it is somehow overwritten with the value `false`. So the resulted output is
```
2 FOUND=0
2 FOUND=0
1 FOUND=1
2 FOUND=0
3 FOUND=1
```
Finally, variable `found` gets the correct value at the end of the for loop.
Interestingly, if using `int` instead of `bool`, no such error occurs.

**Comment by drmortalwombat** [comment]
Fix checked in, please verify.

**Comment by kovzol** [comment]
Thanks, now it works correctly.
