### ISSUE TITLE
hscrollshmup.c compiling and running under linux problem

### ISSUE THREAD

**Issue by marioc8** [drmortalwombat/oscar64#3]
> $ ../../bin/oscar64 hscrollshmup.c -O2

Output prg file, but when run on emulator it only shows for a small part of a second game and then get out to clear screen with READY and flickering cursor.

> $ ../../bin/oscar64 hscrollshmup.c -O2 -n
oscar64: ../oscar64/NumberSet.h:59: bool NumberSet::operator[](int) const: Assertion `elem >= 0 && elem < size' failed.
Aborted (core dumped)

Dumps core. No output prg file.

Other samples from directory "games" and "hires" works and every other sample compiles.

Ubuntu 20.04

**Comment by drmortalwombat** [comment]
Fixed
