### ISSUE TITLE
Any chance of a simple top-down tilemap example?

### ISSUE THREAD

**Issue by shinaka** [drmortalwombat/oscar64#31]
Came across this project the other day after looking for C options on C64. The examples you've included are extremely helpful! I was wondering if it would be possible to add a top-down example (like Zelda 1) with a map from CharPad. I'm trying to retrofit the horizontal schmup example, but I'm a bit lost on how the scrolling works there.

Either way, great work!

**Comment by drmortalwombat** [comment]
There are examples in [The Oscat Tutorials Project](https://github.com/drmortalwombat/OscarTutorials) , look for 1270 and 1280

**Comment by shinaka** [comment]
Ooo! Fantastic! Thank you!

**Comment by drmortalwombat** [comment]
You are welcome

**Comment by polluks** [comment]
Maybe you should add a link to the readme?

**Comment by drmortalwombat** [comment]
From the tutorial to the readme of the compiler ?

**Comment by polluks** [comment]
I mean from the compiler to the tutorial...

Am Di., 5. Dez. 2023 um 09:08 Uhr schrieb drmortalwombat <
***@***.***>:
