### ISSUE TITLE
Doubt about size of prg in some programs when place data in fixed location

### ISSUE THREAD

**Issue by dozznar** [drmortalwombat/oscar64#4]
Hi!

I'm testing your fantastic compiler and I have a doubt. In some programs that use data in a fixed memory such as "charsetcopy" (in samples)

When compile the code, the prg size is 49KB! What is the reason of huge size? 

I have been testing the compiler with my own programs that do something similar and I get the same results (very large prg)
It seems to happen when placing data in high memory addresses. Is it normal behavior?

Thank you for your great work with this tool. I hope that many people will be encouraged to make games with it.

**Comment by drmortalwombat** [comment]
There are no sections in a C64 prg file, just one section from 0x0801 to wherever your code/data ends.  So if you have a section that is high up in memory, the compiler/linker will need to fill the range with zeros.  There are .prg compressors for the C64 such as exomizer that compress .prg and decompress them after loading.  They work very well with the large zero range.
At one point in the near future I will add compression to the linker itself (similar to the existing lzo compressed data sections, but transparent to the user).

**Comment by dozznar** [comment]
Ok understood, I know exomizer. I'll try to compress it. Doubt clarified, thank you very much!
