### ISSUE TITLE
Message for invalid command line arguments

### ISSUE THREAD

**Issue by soegaard** [drmortalwombat/oscar64#42]
Invoking `oscar64` with an invalid command line argument shows this message:

> % ./oscar64 --help
> (null)(0, 0) : error 3004: Invalid command line argument '--help'

**Comment by drmortalwombat** [comment]
What would be the expected behaviour?

**Comment by soegaard** [comment]
I was expecting to see `oscar64` instead of "null)(0, 0) : error 3004:".


Here is the output from `cat` when it is given an illegal option.
Note that it also prints a short usage guide.

> > cat -foobar
> cat: illegal option -- f
> usage: cat [-belnstuv] [file ...]

**Comment by polluks** [comment]
Well, my cat does not print its usage, there is no best practice
```
$ cat -foobar
cat: invalid option -- 'f'
Try 'cat --help' for more information.

**Comment by drmortalwombat** [comment]
My cat usually meows when treated wrong

**Comment by drmortalwombat** [comment]
Changed error format to "oscar64: error ..." when outside of source file
