### ISSUE TITLE
Unsigned Int Issue 

### ISSUE THREAD

**Issue by josipk** [drmortalwombat/oscar64#5]
Unsigned Int is behaving like Singed Int. (Linux build environment)

#include <conio.h>
#include <stdio.h>
#include <c64/types.h>

int main(void)
{

	unsigned int n = 32760;
	int i;

	for(i=0; i<10; i++) {
		n++;
		printf("%d\n",n);
	}
	return 0;
}

output:
32761
32762
32763
32764
32765
32766
32767
-32768
-32767
-32766

**Comment by drmortalwombat** [comment]
This is expected behaviour.  The int type is 16 bit, and if you print it as signed with the %d you get the first bit interpreted as -32768.  You might want to use the %u formatter in the printf to get an unsigned result.

**Comment by josipk** [comment]
OK, so incorrect printf format. Thank You.

**Comment by josipk** [comment]
One more question, does the sqrt function work correctly with unsigned int?

**Comment by drmortalwombat** [comment]
It appears unsiged int to float does not work.  But you can use Dijkstras integer square root instead: `// Integer square root based on Dijkstras algorithm

unsigned tsqrt(unsigned n)
{
    unsigned p, q, r, h;

    p = 0;
    r = n;

#assign q 0x4000
#repeat
    {
        h = p | q;
        p >>= 1;
        if (r >= h)
        {
            p |= q;
            r -= h;
        } 
    }
#assign q q >> 2
#until q == 0
#undef q

    return p;
}
`

**Comment by drmortalwombat** [comment]
There is also a version in <gfx/bitmaph.>
`// Fast unsigned integer square root
unsigned bm_usqrt(unsigned n);`

**Comment by josipk** [comment]
Thank You, btw. the compiler is awesome :)
