### ISSUE TITLE
Optimizations on level  O2,O3,Os are not stable

### ISSUE THREAD

**Issue by adaumann** [drmortalwombat/oscar64#57]
Hello,

I'm developing a kind of pinball game with Oscar64 which is orientated on the game Peggle, the physics are running fine now and I would like to add more game objects but the memory is running out. If I use the optimizer o2,o3 or os the code is 10kb less which would really help but unfortunatly the game is no longer runnable. I cannot tell what the reason is but I used a lot floating numbers (of course). I can provide the source code to test if you like. 

Andy 

Current state:
![8mgwzq](https://github.com/drmortalwombat/oscar64/assets/94932945/cc3c9d78-53c7-422e-af42-3e7432c9d8bb)

**Comment by drmortalwombat** [comment]
Providing the source code will help me determine the issue.

**Comment by adaumann** [comment]
Here is the little prototype: 
[balls.zip](https://github.com/drmortalwombat/oscar64/files/14954342/balls.zip)

**Comment by drmortalwombat** [comment]
Fixed

**Comment by drmortalwombat** [comment]
BTW there is an issue in your vec2_rotate, you change the x component before using it to calculate the y component

**Comment by adaumann** [comment]
That was quick... I assume that it in the next release. Hopefully I can add enough gaming elements and a more pleasant presentation to make it a good gameplay , before the memory runs out
Thank you

**Comment by drmortalwombat** [comment]
Release is already up
