### ISSUE TITLE
feature: Atari XE/XL target machine, file header

### ISSUE THREAD

**Issue by tebe6502** [drmortalwombat/oscar64#6]
memory layout XE/XL:
- free memory area on page zero $80..$FF
- program: $2000..$CFFF (memory area $0700..$1FFF is most commonly occupied by DOS)
- without DOS, program $0980..$CFFF (memory area $0700..$097F is most commonly occupied by FILE DOS LOADER)

Atari XE/XL DOS file header:
- at the beginning of the file (6 bytes)

    $FF,$FF,lo(start_address), hi(start_address), lo(end_address-1), hi(end_address-1)

**Comment by drmortalwombat** [comment]
Implemented as -tm=atari
