### ISSUE TITLE
Preprocessor bug

### ISSUE THREAD

**Issue by AGPX** [drmortalwombat/oscar64#61]
Hello,

the following simple code gives a compilation error:

```
#ifdef GNU_GCC
        // IT SHOULD IGNORE EVERYTHING IS INSIDE HERE!!
	asm__( R"(

		
	)" : : :);
#else
		// It should only consider this!!!
#endif

int main()
{
	return 0;
}
```

The error is:

```
C:\tmp>oscar64 code.cpp
C:/tmp/code.cpp(3, 9) : error 3006: Invalid string literal mode
C:/tmp/code.cpp(3, 9) : error 3006: String constant not terminated
C:/tmp/code.cpp(6, 3) : error 3006: String constant not terminated
```

Looks like that the double quote is the problem. The symbol GNU_GCC is not defined and so all the characters inside the` #ifdef #else` section should be totally ignored.

**Comment by drmortalwombat** [comment]
Fix checked in.  Thank you for reporting, please close the bug report once you verified that it is fixed.
