### ISSUE TITLE
Missing features/defines like `goto` or `NULL`.

### ISSUE THREAD

**Issue by everslick** [drmortalwombat/oscar64#69]
If this is missing *on purpose*, then it should maybe be documented in the README?

Cheers!

**Comment by drmortalwombat** [comment]
NULL Is defined in stddef.h - and yes "goto" is missing on purpose.  If there is demand for a goto, I will look into it.

**Comment by everslick** [comment]
thx, I missed the stddef.h include.

I find `goto` very helpful for function cleanup code and early exit from nested loops. I'm aware that many find this 'unclean'. Nevertheless it's in the language so I vote for including it. ;-)

**Comment by drmortalwombat** [comment]
While goto is quite trivial in C, it is complex in C++ due to the constructor/destructor requirementes when entering/leaving scopes, so it may be a while before I muster the courage to implement it.

**Comment by drmortalwombat** [comment]
Added goto as keyword with an unimplemented error message

**Comment by Kopromaster** [comment]
> NULL Is defined in stddef.h - and yes "goto" is missing on purpose. If there is demand for a goto, I will look into it.

Although I normally don't use goto in manually written code, it's very useful for generated sources, so I'd appreciate it too :-)

**Comment by drmortalwombat** [comment]
Added goto with latest check in (including destructor invocation in C++), please test.

**Comment by everslick** [comment]
Thanks. Will do so. May take until friday though.

**Comment by everslick** [comment]
Tested and works -> closing. Thank you for your great work!
