### ISSUE TITLE
Accept -D (upper case) command line parameter.

### ISSUE THREAD

**Issue by everslick** [drmortalwombat/oscar64#70]
For compatibility with other compilers please consider accepting `-D` in addition to `-d` for defining macros on the command line.

**Comment by drmortalwombat** [comment]
Added -D<space>name and -D<space>name=value defines with latest checkin

**Comment by everslick** [comment]
I believe this line:

https://github.com/drmortalwombat/oscar64/blob/main/oscar64/oscar64.cpp#L256

should be changed to

```
else if (arg[1] == 'd' || arg[1] == 'D')
```

also.

Otherwise **-D** would require a space afterwards which is almost never done. See the test case below:

```
clemens@alien:~$ cat main.c 
#include <stdio.h>

int main(void) {
  return (BLA);
}
```

compiled without any **-D** fails as expected:

```
clemens@alien:~$ gcc main.c 
main.c: In function ‘main’:
main.c:4:11: error: ‘BLA’ undeclared (first use in this function)
    4 |   return (BLA);
      |           ^~~
main.c:4:11: note: each undeclared identifier is reported only once for each function it appears in
```

compiling with `-D BLA=0` works:

```
clemens@alien:~$ gcc -D BLA=0  main.c 
```

compiling with `-DBLA=0` works also:

```
clemens@alien:~$ gcc -DBLA=0  main.c 
```

**Comment by drmortalwombat** [comment]
Changed checked in

**Comment by everslick** [comment]
Thanks
