### ISSUE TITLE
Incomplete Windows delivery

### ISSUE THREAD

**Issue by Kopromaster** [drmortalwombat/oscar64#71]
Delivery based on MSVC is missing at least one .dll library: api-ms-win-core-version-l1-1-1.dll.

Could you please check .msi installer on clear PC without Visual Studio or other manually installed libs / apps and embed all missing .dlls into the delivery package? There could be missing more libs, my PC just stopped after the fist error, so I'm reporting just the first one.

![Výstřižek](https://github.com/drmortalwombat/oscar64/assets/173383522/fd28ec99-d928-4385-86e3-bba7aa359cba)

**Comment by drmortalwombat** [comment]
So which version of window is this?

**Comment by drmortalwombat** [comment]
This dll should be part of Windows 8.1 or later.  If you run Windows 7 or 8 you can install the SDK if you are unwilling to upgrade.

**Comment by Kopromaster** [comment]
I use GCC-compiled version which works fine and I'm just reporting observed issue :-) Nevertheless, generally applications shall run without installing anything. Please consider that lots of developers for ancient computers also don't use most recent PC for development. So the simpliest solution is just to embed missing libs to the installation package.

**Comment by drmortalwombat** [comment]
Installing a operating system library (of a specific) with an application installer is a sure way to dll hell, so I will not do this.  I will add a comment to the readme stating Windows 10 as the minimum operating system version for the installer
