### ISSUE TITLE
Feature request: automatically converting from ASCII to PETSCII

### ISSUE THREAD

**Issue by everslick** [drmortalwombat/oscar64#72]
In my project (https://github.com/everslick/push) I (try to) support multiple platforms and compilers and until now they all convert ASCII to their platform specific representation automatically. For example CC65's documentation states:

`Each literal string and each literal character in the source is translated by use of a translation table.`

I understand that **oscar64** has the `p` (and `P`?) prefix for converting string literals from ASCII to PETSCII which has two issues for me. First: It makes it difficult to have portable code. Second: As I tried to work around this by wrapping each string literal into a macro like:

```
#ifdef OSCAR64
#define ASC(_STR_) p##_STR_
#else
#define ASC(_STR_) _STR_
#endif
```

It did not work either:

```
clemens@alien:~/Devel/8bit/push/src$ make o64
make SDK=oscar64 MACHINE=c64 oscar64
make[1]: Entering directory '/home/clemens/Devel/8bit/push/src'
oscar64 -o=push-o64.prg -tf=prg -tm=c64 -DVERSION=0.0.2 -DHAVE_CONIO -DHAVE_HINTS -DHAVE_OSD -DOSCAR64 -DNOFLOAT -DNOLONG -DC64 -DHAVE_PETSCII -DTOOLCHAIN=oscar64 -DMACHINE=c64 -i=../../oscar64/include/c64 main.c term.c lined.c cli.c parse.c screen.c str.c
/home/clemens/Devel/8bit/push/src/cli.c(418, 1) : error 3005: Unknown identifier 'p"cd"'
/home/clemens/Devel/8bit/push/src/cli.c(419, 1) : error 3005: Unknown identifier 'p"mv"'
/home/clemens/Devel/8bit/push/src/cli.c(420, 1) : error 3005: Unknown identifier 'p"rm"'
/home/clemens/Devel/8bit/push/src/cli.c(421, 1) : error 3005: Unknown identifier 'p"mkdir"'
/home/clemens/Devel/8bit/push/src/cli.c(422, 1) : error 3005: Unknown identifier 'p"rmdir"'
/home/clemens/Devel/8bit/push/src/cli.c(423, 1) : error 3005: Unknown identifier 'p"realpath"'
/home/clemens/Devel/8bit/push/src/cli.c(424, 1) : error 3005: Unknown identifier 'p"basename"'
/home/clemens/Devel/8bit/push/src/cli.c(425, 1) : error 3005: Unknown identifier 'p"dirname"'
/home/clemens/Devel/8bit/push/src/cli.c(426, 1) : error 3005: Unknown identifier 'p"mount"'
/home/clemens/Devel/8bit/push/src/cli.c(427, 1) : error 3005: Unknown identifier 'p"parse"'
/home/clemens/Devel/8bit/push/src/cli.c(428, 1) : error 3005: Unknown identifier 'p"echo"'
make[1]: *** [Makefile:117: oscar64] Error 20
make[1]: Leaving directory '/home/clemens/Devel/8bit/push/src'
make: *** [Makefile:144: o64] Error 2
```

Thus I propose a compiler switch that turns on automatic string conversation, so the `p` prefix is not needed anymore. Bonus points if then maybe prefixing a string with `a` or `A` (i.e. `a"foobar"` for ASCII) would disable automatic PETSCII conversion. ;-)

Or maybe there is another way to accomplish what I need? I'm very open to suggestions! Thanx!

**Comment by drmortalwombat** [comment]
There is already the -psci option, does this work as you need it ?

**Comment by everslick** [comment]
oh, dammit! I completely overlooked that one. Yes, it works. thank you very much!
