### ISSUE TITLE
The parser loses an embedded `\0` in string literals if string concatination is used at the same time.

### ISSUE THREAD

**Issue by everslick** [drmortalwombat/oscar64#73]
The following test program should print `FOO=FOO, BAZ=FOO` but it prints `FOO=FOO, BAZ=FOOBAR` instead.

```
clemens@alien:~/Devel/8bit$ cat test.c 
#include <stdio.h>

int main(void) {
  const char *foo = "foo\0bar";
  const char *baz = "foo\0" "bar";

  printf("foo=%s, baz=%s\n", foo, baz);

  return 0;
}
```

`oscar64 -o=test.prg -tm=c64 -tf=prg -psci test.c`

![Screenshot at 2024-07-07 18-52-09](https://github.com/drmortalwombat/oscar64/assets/1909551/e4e06eb0-63a3-496e-a42a-06adef96a7b8)

**Comment by drmortalwombat** [comment]
Fix checked in

**Comment by everslick** [comment]
That was quick! :)
