### ISSUE TITLE
Programmatic breakpoint

### ISSUE THREAD

**Issue by AGPX** [drmortalwombat/oscar64#75]
Hi,

It would be nice if you could include some sort of symbol/instruction/comment to create a programmatic breakpoint. Something like this:

```
void myfunc()
{
    for (int i = 0; i < 10; ++i)
    {
        ...
        breakpoint();
        ...
    }
}
```

The compiler should determine its address and then output it to the .lbl file, for example:

`break 123f`

so that VICE automatically stops at that address (maybe the compiler can output a single NOP in that address, if this made the thing easier to implement).

That would be very useful.

**Comment by drmortalwombat** [comment]
Implemented and checked in.  Please note, that the "breakpoint" may change the behaviour of the optimizer to avoid having it moved into unexpected places.  It may also provide load/store movement across the breakpoint.
