### ISSUE TITLE
Floating point is somehow defect with version from 29. Aug

### ISSUE THREAD

**Issue by adaumann** [drmortalwombat/oscar64#85]
Hello,

I tried the new version from 29.8. Now my floating point functions are not working properly anymore. Going back to the previous version, everthing is correct.

Andy

**Comment by drmortalwombat** [comment]
Can you provide a sample that does not work?

**Comment by adaumann** [comment]
Hello,

here is an example using the Quake3 square root estimation function, with the old compiler the values between sqrt and qsqrt are minimal different. Starting with version from 29.8 the qsqrt function delivers wrong results:

´´´
#include <c64/cia.h>

#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>


// from QUAKE3
float qsqrt( float number )
{
  long i;
  float x2, y;
  const float threehalfs = 1.5;

  x2 = number * 0.5;
  y  = number;
  i  = * ( long * ) &y;
  i  = 0x5f3759df - ( i >> 1 );
  y  = * ( float * ) &i;
  y  = y * ( threehalfs - ( x2 * y * y ) );

  return 1/y;
}

int main(void)
{


  for(float x = 0; x += 1; x < 10)
  {
    for(float y = 0; y += 1; y < 10)
    {
      float d = sqrt(x * x + y * y);
      float e = qsqrt(x * x + y * y);
    	printf("X=%f Y=%f\n   D=%f E=%f\n", x, y, d,e);
    }
  }
}
´´´

**Comment by drmortalwombat** [comment]
Fix checked in, please verify
