### ISSUE TITLE
Crash when declaring a single element lambda array

### ISSUE THREAD

**Issue by AGPX** [drmortalwombat/oscar64#89]
Hi,

the following simple code:

```
#include <opp/functional.h>

class Actor
{
public:
    opp::function<void(void)> l;
};

class Level
{
public:
    Actor player[1];
};

int main()
{
    Level test;	
    return 0;
}

```

leads the compiler to crash (with any optimization level). Weird facts:

1. if you increase the array size of "player" to a number > 1, it doesn't crash;
2. if you remove the array (declaring a single Actor instance), it doesn't crash;
3. if you remove the lambda from the class Actor (replacing it with another type), it doesn't crash;

**Comment by drmortalwombat** [comment]
Fix checked in, please verify

**Comment by AGPX** [comment]
Ok, now it works. Thanks.
