### ISSUE TITLE
Switch crash

### ISSUE THREAD

**Issue by AGPX** [drmortalwombat/oscar64#92]
Hi,

the following code crashes the compiler:

```
int main()
{
    char a = *((volatile unsigned char *)0x400);
    switch (a)
    {
        default:
        {
            *((volatile unsigned char *)0xd020) = 4;
            break;
        }
    }
    return 0;
}
```

That is, when you have only the default. Idem, if you have a switch without cases at all. Ok, it's not an useful switch, but a serious compiler shouldn't crash ;-)

**Comment by drmortalwombat** [comment]
Fix checked in.

**Comment by AGPX** [comment]
Ok, now it doesn't crash anymore.
